name: Build
on:
  workflow_call:
    inputs:
      cache:
        description: "(boolean) use actions/cache"
        required: false
        default: true
        type: boolean
      node_version:
        description: "(string) "
        required: false
        default: "lts/*"
        type: string
      runs_on:
        description: "(string) "
        required: false
        default: "ubuntu-latest"
        type: string

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.runs_on }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: |
          pnpm run build
          touch .gitkeep

      - uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          compression-level: 1
          name: artifact
          path: |
            dist
            .gitkeep
