# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: ""
        required: true
        default: "keep current"
        type: choice
        options:
          - keep current

  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - uses: pnpm/action-setup@v2
        name: Install pnpm

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: |
            ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm i

      - name: Test
        run: pnpm run test

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          # node-version: "lts/*"
          registry-url: https://registry.npmjs.org/

      - run: npm publish --provenance --access public --registry=https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-ghp:
    needs: test
    runs-on: ubuntu-latest
    env:
      SCOPE: "@${{github.repository_owner}}"
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          # node-version: "lts/*"
          registry-url: "https://npm.pkg.github.com/"
          # Defaults to the user or organization that owns the workflow file
          scope: ${{env.SCOPE}}
          token: ${{secrets.GITHUB_TOKEN}}
          always-auth: true

      - name: rename package name
        run: |
          node scripts/renamePackage.mjs

      - run: npm publish --access public --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
